CREATE DATABASE EMPLOYEE22;
USE EMPLOYEE22;

CREATE TABLE DEPT (
    DEPTNO INT PRIMARY KEY,
    DNAME VARCHAR(40),
    DLOC VARCHAR(40)
);

CREATE TABLE EMPLOYEE22 (
    EMPNO INT PRIMARY KEY,
    ENAME VARCHAR(40),
    MGR_NO INT,
    HIREDATE DATE,
    SAL DECIMAL(10,2),
    DEPTNO INT,
    FOREIGN KEY (DEPTNO) REFERENCES DEPT(DEPTNO)
);

CREATE TABLE PROJECT (
    PNO INT PRIMARY KEY,
    PLOC VARCHAR(40),
    PNAME VARCHAR(50)
);

CREATE TABLE ASSIGNED_TO (
    EMPNO INT,
    PNO INT,
    JOB_ROLE VARCHAR(40),
    PRIMARY KEY (EMPNO, PNO),
    FOREIGN KEY (EMPNO) REFERENCES EMPLOYEE22(EMPNO),
    FOREIGN KEY (PNO) REFERENCES PROJECT(PNO)
);

CREATE TABLE INCENTIVES (
    EMPNO INT,
    INCENTIVE_DATE DATE,
    INCENTIVE_AMOUNT DECIMAL(10,2),
    FOREIGN KEY (EMPNO) REFERENCES EMPLOYEE22(EMPNO)
);


INSERT INTO DEPT VALUES
(10, 'HR', 'Bengaluru'),
(20, 'Finance', 'Hyderabad'),
(30, 'IT', 'Mysuru'),
(40, 'Marketing', 'Chennai'),
(50, 'R&D', 'Bengaluru'),
(60, 'Admin', 'Hyderabad');

INSERT INTO EMPLOYEE22 VALUES
(101, 'Amit', 1001, '2020-01-15', 60000, 10),
(102, 'Priya', 1005, '2019-03-22', 55000, 20),
(103, 'Rahul', 1001, '2021-07-10', 50000, 30),
(104, 'Sneha', 1003, '2018-11-29', 52000, 30),
(105, 'Kiran', 1005, '2022-02-18', 48000, 20),
(106, 'Rhea', 1010, '2019-08-14', 65000, 50),
(107, 'Arjun', 1001, '2023-04-03', 45000, 10);

INSERT INTO PROJECT VALUES
(1001, 'Bengaluru', 'ERP Upgrade'),
(1002, 'Hyderabad', 'FinTrack'),
(1003, 'Mysuru', 'AI System'),
(1004, 'Chennai', 'Market Analysis'),
(1005, 'Bengaluru', 'Cloud Infra'),
(1006, 'Hyderabad', 'Automation');

INSERT INTO ASSIGNED_TO VALUES
(101, 1001, 'Manager'),
(102, 1002, 'Analyst'),
(103, 1003, 'Developer'),
(104, 1003, 'Tester'),
(105, 1002, 'Accountant'),
(106, 1005, 'Developer'),
(107, 1001, 'HR Executive'),
(103, 1001, 'Developer');

INSERT INTO INCENTIVES VALUES
(101, '2024-01-30', 5000),
(102, '2024-02-12', 3000),
(105, '2024-01-18', 2000);

-- iii

SELECT DISTINCT A.EMPNO
FROM ASSIGNED_TO A
JOIN PROJECT P ON A.PNO = P.PNO
WHERE P.PLOC IN ('Bengaluru', 'Hyderabad', 'Mysuru');

-- iv
SELECT EMPNO
FROM EMPLOYEE22
WHERE EMPNO NOT IN (SELECT EMPNO FROM INCENTIVES);

-- v
SELECT E.EMPNO, E.ENAME, E.DEPTNO, D.DLOC AS DEPT_LOCATION,
       A.JOB_ROLE, P.PNO, P.PLOC AS PROJECT_LOCATION
FROM EMPLOYEE22 E
JOIN DEPT D ON E.DEPTNO = D.DEPTNO
JOIN ASSIGNED_TO A ON E.EMPNO = A.EMPNO
 JOIN PROJECT P ON A.PNO = P.PNO
WHERE D.DLOC = P.PLOC;

  -- iii List managers with maximum employees
SELECT M.ENAME AS Manager_Name
FROM EMPLOYEE22 M
JOIN EMPLOYEE22 E ON M.EMPNO = E.MGR_NO
GROUP BY M.EMPNO, M.ENAME
HAVING COUNT(E.EMPNO) = (
    SELECT MAX(emp_count)
    FROM (
        SELECT MGR_NO, COUNT(*) AS emp_count
        FROM EMPLOYEE22
        WHERE MGR_NO IS NOT NULL
        GROUP BY MGR_NO
    ) AS t
);

-- iv Managers whose salary > average salary of their employees
SELECT M.ENAME AS Manager_Name, M.SAL
FROM EMPLOYEE M
JOIN EMPLOYEE E ON M.EMPNO = E.MGR_NO
GROUP BY M.EMPNO, M.ENAME, M.SAL
HAVING M.SAL > AVG(E.SAL);

-- V Second top-level manager of each department
SELECT DEPTNO, ENAME AS Second_Top_Manager
FROM (
    SELECT M.DEPTNO, M.ENAME,
           DENSE_RANK() OVER (PARTITION BY M.DEPTNO ORDER BY M.SAL DESC) AS rnk
    FROM EMPLOYEE M
    WHERE M.EMPNO IN (SELECT DISTINCT MGR_NO FROM EMPLOYEE)
) AS x
WHERE rnk = 2;

-- vi
SELECT E.*
FROM EMPLOYEE E
JOIN (
    SELECT EMPNO, INCENTIVE_AMOUNT,
           DENSE_RANK() OVER (ORDER BY INCENTIVE_AMOUNT DESC) AS rnk
    FROM INCENTIVES
    WHERE YEAR(INCENTIVE_DATE)=2019
      AND MONTH(INCENTIVE_DATE)=1
) T ON E.EMPNO = T.EMPNO
WHERE rnk = 2;

-- vii Employees working in same department as their manager
SELECT E.EMPNO, E.ENAME, E.DEPTNO
FROM EMPLOYEE E
JOIN EMPLOYEE M ON E.MGR_NO = M.EMPNO
WHERE E.DEPTNO = M.DEPTNO;

